
dataset: 'electronic'
data_path: 'data/'
log_path: 'log/process.log'
temp_path: 'temp/'


model: 'gpt-3.5-turbo'
api_key: ''
temperature: 0.
feedback_iteration: 4
rater:
  - 'openai':
      model: 'gpt-3.5-turbo'
      temperature: 0.
      api_key: 'sk-jaMNL109Qb9M6AIQGGwxWJ8ayIhQVx2NWY2poW0kPS1ltd8w'

  - 'claude':
      model: 'claude-2'
      temperature: 0.
      api_key: ''

